version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
