#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JAVA_REPO="${PAIMON_JAVA_REPO:-${REPO_ROOT}/../paimon}"
RUST_GOLDEN="${REPO_ROOT}/crates/paimon/src/fm_index/fmindex-v1-golden.base64"
JAVA_GENERATOR="${REPO_ROOT}/scripts/fm-index/FMIndexV1GoldenGenerator.java"
MODE="generate"

if [[ "${1:-}" == "--check" ]]; then
  MODE="check"
  shift
fi
if [[ $# -gt 0 ]]; then
  JAVA_REPO="$1"
  shift
fi
if [[ $# -gt 0 ]]; then
  echo "Usage: $0 [--check] [path-to-paimon-java]" >&2
  exit 2
fi
if [[ ! -f "${JAVA_REPO}/pom.xml" ]]; then
  echo "Paimon Java repository not found at ${JAVA_REPO}." >&2
  echo "Pass its path as the final argument or set PAIMON_JAVA_REPO." >&2
  exit 2
fi
JAVA_GOLDEN="${JAVA_REPO}/paimon-common/src/test/resources/fmindex-v1-golden.base64"
if [[ ! -f "${JAVA_GOLDEN}" ]]; then
  echo "Java FM-index V1 fixture not found at ${JAVA_GOLDEN}." >&2
  exit 2
fi

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/paimon-fm-v1-golden.XXXXXX")"
cleanup() {
  rm -rf -- "${WORK_DIR}"
}
trap cleanup EXIT

echo "Generating FM-index V1 bytes with the Java writer"
(
  cd "${JAVA_REPO}"
  mvn -q -pl paimon-common -am \
    -DskipITs \
    -Dspotless.check.skip=true \
    -Dcheckstyle.skip=true \
    -Dtest=FMGlobalIndexTest#testV1NoneGoldenFixtureIsStableAndReadable \
    -Dsurefire.failIfNoSpecifiedTests=false \
    test
)

SUREFIRE_REPORT="${JAVA_REPO}/paimon-common/target/surefire-reports/TEST-org.apache.paimon.globalindex.fmindex.FMGlobalIndexTest.xml"
JAVA_CLASSPATH="$(sed -n 's/.*<property name="surefire.test.class.path" value="\([^"]*\)".*/\1/p' "${SUREFIRE_REPORT}")"
if [[ -z "${JAVA_CLASSPATH}" ]]; then
  echo "Could not read the Java test classpath from ${SUREFIRE_REPORT}." >&2
  exit 1
fi

GENERATOR_CLASSES="${WORK_DIR}/classes"
JAVA_INDEX="${WORK_DIR}/fmindex-v1-java.index"
mkdir -p "${GENERATOR_CLASSES}"
javac -cp "${JAVA_CLASSPATH}" -d "${GENERATOR_CLASSES}" "${JAVA_GENERATOR}"
java -cp "${GENERATOR_CLASSES}:${JAVA_CLASSPATH}" \
  org.apache.paimon.globalindex.fmindex.FMIndexV1GoldenGenerator "${JAVA_INDEX}"

GENERATED_BASE64="${WORK_DIR}/fmindex-v1-golden.base64"
base64 < "${JAVA_INDEX}" | tr -d '\n' > "${GENERATED_BASE64}"
printf '\n' >> "${GENERATED_BASE64}"
if ! cmp -s "${GENERATED_BASE64}" "${JAVA_GOLDEN}"; then
  echo "Standalone Java generator differs from Java's canonical V1 fixture." >&2
  exit 1
fi

if [[ "${MODE}" == "check" ]]; then
  if ! cmp -s "${GENERATED_BASE64}" "${RUST_GOLDEN}"; then
    echo "Rust golden fixture differs from the Java-generated V1 bytes." >&2
    exit 1
  fi
  echo "Checked-in Rust golden matches the Java-generated bytes"
else
  cp "${GENERATED_BASE64}" "${RUST_GOLDEN}"
  echo "Updated ${RUST_GOLDEN} from the Java-generated bytes"
fi

echo "Verifying the Java golden with the Rust reader and writer"
(
  cd "${REPO_ROOT}"
  cargo test -p paimon --lib \
    fm_index::tests::java_generated_v1_golden_is_bidirectionally_compatible -- --exact
)
