// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use super::*;
use crate::file_index::file_index_result::FileIndexResult;
use crate::file_index::range_bitmap::RangeBitmapFileIndexReader;
use crate::spec::PredicateOperator;

fn selection(rows: impl IntoIterator<Item = u32>) -> FileIndexResult {
    FileIndexResult::Selection(rows.into_iter().collect())
}

fn data_type(name: &str) -> DataType {
    serde_json::from_value(serde_json::Value::String(name.to_string())).unwrap()
}

#[test]
fn java_chunk_and_container_golden_payloads() {
    use sha2::{Digest, Sha256};

    // Generated by fixtures/GenerateRangeBitmap.java against Java Paimon 1d368b4a5
    // with RoaringBitmap 1.2.1. Hash the entire payload, including all headers.
    let ints = vec![
        Some(9),
        Some(-1),
        Some(3),
        None,
        Some(1),
        Some(7),
        Some(5),
        Some(3),
        Some(i32::MIN),
        Some(i32::MAX),
    ]
    .into_iter()
    .map(|v| v.map(Datum::Int))
    .collect::<Vec<_>>();
    let strings = [
        Some("z"),
        Some(""),
        Some("a\0"),
        None,
        Some("你好"),
        Some("ab"),
        Some("abc"),
        Some("🦀"),
    ]
    .into_iter()
    .map(|v| v.map(|v| Datum::String(v.into())))
    .collect();
    let containers = (0..70_000)
        .map(|i| {
            if i % 11 == 0 {
                None
            } else {
                Some(Datum::Int((i * 37) % 101))
            }
        })
        .collect();
    for (name, size, values, digest) in [
        (
            "INT",
            "0b",
            vec![],
            "930b0b08191aa151e382586494360c5408fc7d4e2fd6971e0637004e2099e017",
        ),
        (
            "INT",
            "0b",
            vec![None; 3],
            "ca2a1588451c1c3c353abd33b7f447721bf61f65ce06c8d004646821c4123edd",
        ),
        (
            "INT",
            "0b",
            vec![Some(Datum::Int(7)), None, Some(Datum::Int(7))],
            "69007c0772b87a68420a8ed271849a45072e7868c1ba2fe972d3e7a4c9be850f",
        ),
        (
            "INT",
            "0b",
            ints.clone(),
            "82999022f0517a867a0d2a109467de891c0d11a41f20e207c8502d7b31414e21",
        ),
        (
            "INT",
            "8b",
            ints,
            "b5b2b34a69e6c25ca7cf8bbb799df142b44d1c9011840fa2862fef996f2c4892",
        ),
        (
            "VARCHAR(100)",
            "8b",
            strings,
            "11cc7028788d995ca15b8d94bdd7c91dd9ba1110a941cfce7b8412bcfc7b3f5f",
        ),
        (
            "INT",
            "12b",
            containers,
            "668a624b4c77633891f7280529ce3344149a9efb6ac2509b78c75ceca3bfe59e",
        ),
    ] {
        let mut options = Options::new();
        options.set("chunk-size", size);
        let mut writer = RangeBitmapFileIndexWriter::try_new(data_type(name), &options).unwrap();
        for value in values {
            writer.write(value.as_ref()).unwrap();
        }
        assert_eq!(
            hex::encode(Sha256::digest(writer.serialized_bytes().unwrap())),
            digest,
            "{name}, {size}"
        );
    }
}

#[test]
fn supported_types_round_trip_across_chunks() {
    let cases = [
        ("BOOLEAN", Datum::Bool(false), Datum::Bool(true)),
        ("TINYINT", Datum::TinyInt(i8::MIN), Datum::TinyInt(i8::MAX)),
        (
            "SMALLINT",
            Datum::SmallInt(i16::MIN),
            Datum::SmallInt(i16::MAX),
        ),
        ("INT", Datum::Int(i32::MIN), Datum::Int(i32::MAX)),
        ("BIGINT", Datum::Long(i64::MIN), Datum::Long(i64::MAX)),
        (
            "FLOAT",
            Datum::Float(f32::NEG_INFINITY),
            Datum::Float(f32::INFINITY),
        ),
        (
            "DOUBLE",
            Datum::Double(f64::NEG_INFINITY),
            Datum::Double(f64::INFINITY),
        ),
        (
            "DECIMAL(18, 2)",
            Datum::Decimal {
                unscaled: -999999999999999999,
                precision: 18,
                scale: 2,
            },
            Datum::Decimal {
                unscaled: 999999999999999999,
                precision: 18,
                scale: 2,
            },
        ),
        ("DATE", Datum::Date(-1), Datum::Date(1)),
        ("TIME(3)", Datum::Time(0), Datum::Time(86399999)),
        (
            "TIMESTAMP(3)",
            Datum::Timestamp {
                millis: -1,
                nanos: 0,
            },
            Datum::Timestamp {
                millis: 1,
                nanos: 0,
            },
        ),
        (
            "TIMESTAMP(6)",
            Datum::Timestamp {
                millis: -1,
                nanos: 999000,
            },
            Datum::Timestamp {
                millis: 0,
                nanos: 1000,
            },
        ),
        (
            "TIMESTAMP_LTZ(3)",
            Datum::LocalZonedTimestamp {
                millis: -1,
                nanos: 0,
            },
            Datum::LocalZonedTimestamp {
                millis: 1,
                nanos: 0,
            },
        ),
        (
            "TIMESTAMP_LTZ(6)",
            Datum::LocalZonedTimestamp {
                millis: -1,
                nanos: 999000,
            },
            Datum::LocalZonedTimestamp {
                millis: 0,
                nanos: 1000,
            },
        ),
        (
            "CHAR(10)",
            Datum::String("".into()),
            Datum::String("你好".into()),
        ),
        (
            "VARCHAR(100)",
            Datum::String("a\0".into()),
            Datum::String("🦀".into()),
        ),
    ];
    for (name, low, high) in cases {
        let data_type = data_type(name);
        for size in ["0b", "1b", "8b", "16kb"] {
            let mut options = Options::new();
            options.set("chunk-size", size);
            let mut writer =
                RangeBitmapFileIndexWriter::try_new(data_type.clone(), &options).unwrap();
            for value in [Some(&high), None, Some(&low), Some(&high)] {
                writer.write(value).unwrap();
            }
            let bytes = writer.serialized_bytes().unwrap();
            assert_eq!(bytes, writer.serialized_bytes().unwrap());
            let reader = RangeBitmapFileIndexReader::try_new(data_type.clone(), bytes).unwrap();
            for (op, literals, expected) in [
                (PredicateOperator::Eq, vec![high.clone()], selection([0, 3])),
                (PredicateOperator::Lt, vec![high.clone()], selection([2])),
                (PredicateOperator::Gt, vec![low.clone()], selection([0, 3])),
                (
                    PredicateOperator::Between,
                    vec![low.clone(), high.clone()],
                    selection([0, 2, 3]),
                ),
                (PredicateOperator::IsNull, vec![], selection([1])),
            ] {
                assert_eq!(
                    reader.try_evaluate(&data_type, op, &literals).unwrap(),
                    expected,
                    "{name}, {size}, {op:?}"
                );
            }
        }
    }
}

#[test]
fn ranges_match_unindexed_values_across_bitmap_containers() {
    use rand::{rngs::StdRng, Rng, SeedableRng};
    let data_type = data_type("INT");
    let mut options = Options::new();
    options.set("chunk-size", "12b");
    let mut writer = RangeBitmapFileIndexWriter::try_new(data_type.clone(), &options).unwrap();
    let mut rng = StdRng::seed_from_u64(42);
    let values: Vec<Option<i32>> = (0..70_000)
        .map(|_| {
            if rng.gen_ratio(1, 8) {
                None
            } else {
                Some(rng.gen_range(-1000..=1000))
            }
        })
        .collect();
    for value in &values {
        writer.write(value.map(Datum::Int).as_ref()).unwrap();
    }
    let reader =
        RangeBitmapFileIndexReader::try_new(data_type.clone(), writer.serialized_bytes().unwrap())
            .unwrap();
    for bound in [-1001, -1000, -1, 0, 1, 1000, 1001] {
        for op in [
            PredicateOperator::Eq,
            PredicateOperator::NotEq,
            PredicateOperator::Lt,
            PredicateOperator::LtEq,
            PredicateOperator::Gt,
            PredicateOperator::GtEq,
        ] {
            let expected = values.iter().enumerate().filter_map(|(row, value)| {
                value
                    .filter(|value| match op {
                        PredicateOperator::Eq => *value == bound,
                        PredicateOperator::NotEq => *value != bound,
                        PredicateOperator::Lt => *value < bound,
                        PredicateOperator::LtEq => *value <= bound,
                        PredicateOperator::Gt => *value > bound,
                        PredicateOperator::GtEq => *value >= bound,
                        _ => unreachable!(),
                    })
                    .map(|_| row as u32)
            });
            assert_eq!(
                reader
                    .try_evaluate(&data_type, op, &[Datum::Int(bound)])
                    .unwrap(),
                selection(expected)
            );
        }
    }
}

#[test]
fn empty_null_singleton_and_write_after_serialization() {
    let data_type = data_type("INT");
    let mut writer =
        RangeBitmapFileIndexWriter::try_new(data_type.clone(), &Options::new()).unwrap();
    for nulls in 0..=3 {
        assert_eq!(writer.empty(), nulls == 0);
        let reader = RangeBitmapFileIndexReader::try_new(
            data_type.clone(),
            writer.serialized_bytes().unwrap(),
        )
        .unwrap();
        assert_eq!(
            reader
                .try_evaluate(&data_type, PredicateOperator::IsNull, &[])
                .unwrap(),
            selection(0..nulls)
        );
        assert_eq!(reader.bsi.slices.len(), 64);
        writer.write(None).unwrap();
    }
    writer.write(Some(&Datum::Int(7))).unwrap();
    let reader =
        RangeBitmapFileIndexReader::try_new(data_type.clone(), writer.serialized_bytes().unwrap())
            .unwrap();
    assert_eq!(reader.bsi.slices.len(), 1);
    assert_eq!(
        reader
            .try_evaluate(&data_type, PredicateOperator::Eq, &[Datum::Int(7)])
            .unwrap(),
        selection([4])
    );
}

#[test]
fn rejects_invalid_configuration_values_and_overflow() {
    for name in [
        "DECIMAL(19, 2)",
        "TIMESTAMP(9)",
        "TIMESTAMP_LTZ(9)",
        "BINARY(4)",
        "VARBINARY(4)",
    ] {
        assert!(matches!(
            RangeBitmapFileIndexWriter::try_new(data_type(name), &Options::new()),
            Err(Error::Unsupported { .. })
        ));
    }
    for size in ["-1", "bad", "2gb", "4gb", "9223372036854775807tb"] {
        let mut options = Options::new();
        options.set("chunk-size", size);
        assert!(matches!(
            RangeBitmapFileIndexWriter::try_new(data_type("INT"), &options),
            Err(Error::ConfigInvalid { .. })
        ));
    }
    let mut writer =
        RangeBitmapFileIndexWriter::try_new(data_type("TIMESTAMP(6)"), &Options::new()).unwrap();
    for value in [
        Datum::Int(1),
        Datum::Timestamp {
            millis: 0,
            nanos: 1,
        },
        Datum::Timestamp {
            millis: i64::MAX,
            nanos: 0,
        },
    ] {
        assert!(writer.write(Some(&value)).is_err());
        assert!(writer.empty());
    }
    writer.row_count = i32::MAX as u32;
    assert!(writer.write(None).is_err());
    assert_eq!(writer.row_count, i32::MAX as u32);
    assert!(checked_count(i32::MAX as usize + 1).is_err());
}
